language: java
jdk:
  - oraclejdk11
before_install:
  - sudo apt-get update
  - cd app/
  - echo "Let's starting maven package!"
  - mvn clean package
  - cd ..
  - echo "We are in root dir"
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_HUB_PASSWORD" | docker login --username "$DOCKER_HUB_USERNAME" --password-stdin
deploy:
  provider: script
  script: 
    docker tag docker-from-zero-to-mastery:latest "$DOCKER_HUB_USERNAME"/docker-from-zero-to-mastery:$TRAVIS_JOB_ID
    docker push "$DOCKER_HUB_USERNAME"/docker-from-zero-to-mastery;
  on:
    branch: main
notifications:
  email: false