version: '3.8'
services: 
  db:
    image: postgres:al
    restart: always
    environment: 
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker_from_zero
      TZ: America/Sao_Paulo
    ports:
      - "15432:5432"
    networks: 
      - udemy-network
  docker-from-zero-to-mastery:
    image: docker-from-zero-to-mastery
    restart: always
    build: 
      context: .
      dockerfile: app/Dockerfile
    working_dir: /app
    environment: 
      TZ: America/Sao_Paulo
    ports: 
      - "8080:8080"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks: 
      - udemy-network
networks: 
  udemy-network:
    driver: bridge